<?php
require_once 'funciones.php';

$datos_servicios = [];

$datos_servicios[0] = $_POST['nombreCorreo'] ?? '';
$datos_servicios[1] = $_POST['sede'] ?? '';
$datos_servicios[2] = $_POST['area'] ?? '';
$datos_servicios[3] = $_POST['usuario'] ?? '';
$datos_servicios[4] = $_POST['reporte'] ?? '';
$datos_servicios[5] = $_POST['hardware'] ?? '';
$datos_servicios[6] = $_POST['software'] ?? '';
$datos_servicios[7] = $_POST['instalacion'] ?? '';
$datos_servicios[8] = $_POST['configuracion'] ?? '';
$datos_servicios[9] = $_POST['sin_red'] ?? '';
$datos_servicios[10] = $_POST['ruido'] ?? '';
$datos_servicios[11] = $_POST['sin_linea'] ?? '';
$datos_servicios[12] = $_POST['cableado'] ?? '';
$datos_servicios[13] = $_POST['cambio_numero'] ?? '';
$datos_servicios[14] = $_POST['cambio_aparato'] ?? '';
$datos_servicios[15] = $_POST['otro'] ?? '';
$datos_servicios[16] = $_POST['apartadoTelefonico1'] ?? '';
$datos_servicios[17] = $_POST['apartadoTelefonico2'] ?? '';
$datos_servicios[18] = $_POST['apartadoTelefonico3'] ?? '';
$datos_servicios[19] = $_POST['apartadoTelefonico4'] ?? '';
$datos_servicios[20] = $_POST['apartadoTelefonico5'] ?? '';
$datos_servicios[21] = $_POST['roseta1'] ?? '';
$datos_servicios[22] = $_POST['roseta2'] ?? '';
$datos_servicios[23] = $_POST['roseta3'] ?? '';
$datos_servicios[24] = $_POST['roseta4'] ?? '';
$datos_servicios[25] = $_POST['roseta5'] ?? '';
$datos_servicios[26] = $_POST['tarjetaRed1'] ?? '';
$datos_servicios[27] = $_POST['tarjetaRed2'] ?? '';
$datos_servicios[28] = $_POST['tarjetaRed3'] ?? '';
$datos_servicios[29] = $_POST['tarjetaRed4'] ?? '';
$datos_servicios[30] = $_POST['tarjetaRed5'] ?? '';
$datos_servicios[31] = $_POST['jack1'] ?? '';
$datos_servicios[32] = $_POST['jack2'] ?? '';
$datos_servicios[33] = $_POST['jack3'] ?? '';
$datos_servicios[34] = $_POST['jack4'] ?? '';
$datos_servicios[35] = $_POST['jack5'] ?? '';
$datos_servicios[36] = $_POST['modem1'] ?? '';
$datos_servicios[37] = $_POST['modem2'] ?? '';
$datos_servicios[38] = $_POST['modem3'] ?? '';
$datos_servicios[39] = $_POST['modem4'] ?? '';
$datos_servicios[40] = $_POST['modem5'] ?? '';
$datos_servicios[41] = $_POST['plugs1'] ?? '';
$datos_servicios[42] = $_POST['plugs2'] ?? '';
$datos_servicios[43] = $_POST['plugs3'] ?? '';
$datos_servicios[44] = $_POST['plugs4'] ?? '';
$datos_servicios[45] = $_POST['plugs5'] ?? '';
$datos_servicios[46] = $_POST['cableUp1'] ?? '';
$datos_servicios[47] = $_POST['cableUp2'] ?? '';
$datos_servicios[48] = $_POST['cableUp3'] ?? '';
$datos_servicios[49] = $_POST['cableUp4'] ?? '';
$datos_servicios[50] = $_POST['cableUp5'] ?? '';
$datos_servicios[51] = $_POST['cableUp6'] ?? '';
$datos_servicios[52] = $_POST['cableUp7'] ?? '';
$datos_servicios[53] = $_POST['multipar1'] ?? '';
$datos_servicios[54] = $_POST['multipar2'] ?? '';
$datos_servicios[55] = $_POST['multipar3'] ?? '';
$datos_servicios[56] = $_POST['multipar4'] ?? '';
$datos_servicios[57] = $_POST['multipar5'] ?? '';
$datos_servicios[58] = $_POST['multipar6'] ?? '';
$datos_servicios[59] = $_POST['multipar7'] ?? '';
$datos_servicios[60] = $_POST['persona'] ?? '';
$datos_servicios[61] = $_POST['Observaciones'] ?? '';
$datos_servicios[62] = $_POST['estadoReporte'] ?? '';
$datos_servicios[63] = $_POST['noConcluMotivo'] ?? '';


var_dump($datos_servicios);